### PR TITLE
[DO NOT REVIEW] - Ci/testing danger

### PR DESCRIPTION
**Pull request by tomas-stefano**
I am opening this Pull request to test Danger gem https://github.com/danger/danger

So I am messing up the code because I want to see the warnings from Danger appear on the PR.

### CODE REVIEW

**Comment by masbuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          4 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/evidence_summary.rb</td>
      <td>5</td>
      <td>Layout/IndentationWidth: Use 2 (not 16) spaces for indentation.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/evidence_summary.rb</td>
      <td>17</td>
      <td>Layout/IndentationWidth: Use 2 (not 18) spaces for indentation.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/evidence_summary.rb</td>
      <td>21</td>
      <td>Layout/IndentationWidth: Use 2 (not 16) spaces for indentation.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/evidence_summary.rb</td>
      <td>25</td>
      <td>Layout/IndentationWidth: Use 2 (not 16) spaces for indentation.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There are code changes, but no corresponding tests. Please include tests if this PR introduces any modifications in behavior. If this is a refactor PR, please ignore the message.Refer to our mas standards guides about opening a PR<a href="link-to-the-mas-standards-about-opening-a-pr">here</a></td>
    </tr>
  </tbody>
</table>

At Money Advice Service, we use Danger gem, to ensure that our
commits and pull requests follow  [standards](https://github.com/moneyadviceservice/mas-standards/blob/master/Dangerfile).
If you think one of the points here has been raised in error (or   shouldn't be in our standards), open an issue or pull request on [our   Danger config](https://github.com/moneyadviceservice/mas-standards).


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by osharpe** [comment]
💯

**Comment by willhall88** [comment]
😍

**Comment by tomas-stefano** [comment]
Closing since this PR was only to test danger.

**Pull request closed without merging**
