### PR TITLE
[DEV APPROVED] Adds evaluation types component

### PR DESCRIPTION
**Pull request by johnplayer1982**
# Evaluations Types Component

Adds evaluation types component, and updates search results with ui component dependencies.

**Also**: Updates the search results with the updates evaluation type icons.

| Screenshot |
|------------|
|image|

### CODE REVIEW

**Comment by davidtrussler** [comment]
👍

**Comment by margOnline** [comment]
Looks good! 

I have a question about the use of the xmp tag, which I think we are only using for the styleguide. Is that tag deprecated and if it becomes completely browser unsupported, what would be the alternative approach to rendering the code?

**Comment by johnplayer1982** [comment]
I believe we can use ``<pre>`` or even ``<code>`` will make that adjustment in the very near future

**Comment by margOnline** [comment]
Should we be considering making that adjustment given that `<xmp>` is obsolete in HTML5?

**Comment by johnplayer1982** [comment]
Yea thats what I tried to say above (badly), but wont do it here as the PR will become huge and lose context.  Will be very soon.

**Pull request merged**
