### PR TITLE
[DEV APPROVED] - 8841 Add Cucumber

### PR DESCRIPTION
**Pull request by Tr4pSt3R**
It adds support for creating Gherkin files and step definitions in the future. 

**Note:** 
There are outstanding deprecating warnings on this PR but it's not down to the code itself. The warnings are being produced from strings matching the search criteria of deprecated syntax the `Cucumber-Rails` gem. We are using the latest version of this gem`Cucumber-rails v.1.5.0` meaning there is currently no solution to this issue.

### CODE REVIEW

**Comment by margOnline** [comment]
@Tr4pSt3R I'm getting some deprecation warnings from cucumber re tagged hooks, can these be addressed?

**Comment by Tr4pSt3R** [comment]
@margOnline I went through all the places where it was reporting that there were deprecated stuff and removed them but they are still being reported from elsewhere which means it's coming from another. I have stuck [WIP] on the PR so that I can inspect it more Tomorrow.

**Comment by willhall88** [comment]
Not checked if this is the same issue re depracated hooks, but been watching this issue for a while. Not tried the latest suggestions on the feed yet
https://github.com/cucumber/cucumber-rails/issues/346

**Comment by Tr4pSt3R** [comment]
@willhall88 this is still an [open issue](https://github.com/cucumber/cucumber-rails/issues/346). The bulk of the issue is that these deprecation which is being reported by _Cucumber_ is from other gems. 

https://github.com/cucumber/cucumber-rails/issues/346

**Comment by willhall88** [comment]
yes, if this is the same issue as the one I've listed, then it's because these warnings are coming via different gems. which is frustrating. 
https://github.com/cucumber/cucumber-rails/issues/346#issuecomment-361127404
one of the latest comments might help us identify which gems are causing the warnings and potentially update them though

**Comment by Tr4pSt3R** [comment]
@willhall88 the error is being reported by the Cucumber-Rails gem itself. It contains the `deprecated` tags as part of it's generator template. This is the latest version of the gem; `v1.5.0`. It does not appear in any other app. 

```bash
[jonesagyemang:~/Projects/MAS/fin_cap] 8841_add_cucumber(+3/-0)* 4m51s ± ack '~@javascript' /opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/
/opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-rails-1.5.0/lib/cucumber/rails/hooks/active_record.rb
14:  Before('~@javascript') do

/opt/boxen/rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cucumber-rails-1.5.0/lib/generators/cucumber/install/templates/support/_rails_each_run.rb.erb
36:#   Before('~@no-txn', '~@selenium', '~@culerity', '~@celerity', '~@javascript') do
```

**Comment by willhall88** [comment]
not much we can do then 😭 - what I silly implementation. Give warnings of deprecations and then leave those deprecations in your own codebase.

**Comment by margOnline** [comment]
I tried running `grep -l -r '~@wip'` in my bundler directory to identify any offending gems which timed out. Does someone else want to try @Tr4pSt3R @willhall88?

**Comment by tomas-stefano** [comment]
Hi I really liked this discussions that we are having on this PR, but as a reviewer it is not straight forward for me to try to approve since the PR has just one line description, and a lot of *conclusion* comments. Don't get me wrong, *the comments are good*, but can we not move this communication here to a person conversation or developers/backend_developers channel or even pair and put the conclusions of this talks on the PR description itself? It will much easier to give an good review.

**Pull request merged**
