### PR TITLE
9239 Lifestage page

### PR DESCRIPTION
**Pull request by margOnline**
[TP 9239](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=feature/9239)

Life Stage pages provide a landing page for all the information within the site relating to a particular life_stage e.g. Young Adults, Children and Young People
 
The page type needs to be a selectable option in the CMS with the ability for editors to add/edit content regarding different aspects for each Life Stage. 

### BEFORE MERGING
* [x] [Required CMS changes](https://github.com/moneyadviceservice/cms/pull/456).
* [x] [Task for Research & Evaluation component](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9241)

### Approach

- Extend the base_template and template_presenter for the Life Stage specific view
- Re-use base components and blocks where possible
- Add new methods for lifestage specific components

### Notes for Reviewing
1. For the LifestageTemplatePresenter methods `teaser_text_component` and `teaser_title_component`, I decided not to create tests for the context `when the object does not have the block`. Since I did create a test for that context for the method `teaser_image_component`, it seemed a little redundant to repeat them. However, happy to add them in if reviewers think they are required for completeness.
2. It has been decided to allow this pr to progress without the dynamic Latest News component in order to keep the pr size manageable. A separate [TP ticket](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=task/9297) has been created to update the Latest News component on the Lifestage Page.

### CODE REVIEW

**Comment by masbuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          12 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>config/routes.rb</td>
      <td>11</td>
      <td>Style/SymbolArray: Use <code>%i</code> or <code>%I</code> for an array of symbols.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/presenters/lifestage_template_presenter.rb</td>
      <td>26</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/presenters/lifestage_template_presenter.rb</td>
      <td>30</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/presenters/lifestage_template_presenter.rb</td>
      <td>34</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/templates/lifestage_template.rb</td>
      <td>33</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/templates/lifestage_template.rb</td>
      <td>41</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/templates/lifestage_template.rb</td>
      <td>45</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/templates/lifestage_template.rb</td>
      <td>49</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/templates/lifestage_template.rb</td>
      <td>53</td>
      <td>Lint/DuplicateMethods: Method <code>LifestageTemplate#teaser_title_block</code> is defined at both app/templates/lifestage_template.rb:33 and app/templates/lifestage_template.rb:53.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/templates/lifestage_template.rb</td>
      <td>53</td>
      <td>Naming/UncommunicativeMethodParamName: Method parameter must be at least 3 characters long.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>spec/presenters/lifestage_template_presenter_spec.rb</td>
      <td>12</td>
      <td>Metrics/LineLength: Line is too long. [94/80]</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>spec/presenters/lifestage_template_presenter_spec.rb</td>
      <td>43</td>
      <td>Lint/Debugger: Remove debugger entry point <code>binding.pry</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There are code changes, but no corresponding tests. Please include tests if this PR introduces any modifications in behavior. If this is a refactor PR, please ignore the message.Refer to our mas standards guides about opening a PR<a href="link-to-the-mas-standards-about-opening-a-pr">here</a></td>
    </tr>
  </tbody>
</table>

At Money Advice Service, we use Danger gem, to ensure that our
commits and pull requests follow  [standards](https://github.com/moneyadviceservice/mas-standards/blob/master/Dangerfile).
If you think one of the points here has been raised in error (or   shouldn't be in our standards), open an issue or pull request on [our   Danger config](https://github.com/moneyadviceservice/mas-standards).


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by tomas-stefano** [comment]
Jenkins runs the PR check and then danger erases from Github. But thank you for let me know.

**Comment by margOnline** [comment]
@tomas-stefano Jenkins runs the check when the first pr is opened and Danger updates github. But when subsequent pushes are made to the pr, Danger is not updating github. Those errors are old ones. I have mentioned this to @osharpe and I know he was looking into it, but its kind of low priority compared to what else he is doing.

**Comment by osharpe** [comment]
@margOnline the one we looked at, if I remember correctly you hadn't checked in the updated cassette. The Danger check should clear the comments once the issues are fixed and the Jenkins job PR check runs. Looks like in this case the Jenkins PR job has not run. I have kicked it off now, so it should clear the comments if the issues have been addressed.

**Pull request merged**
