### PR TITLE
Remove spring gem

### PR DESCRIPTION
**Pull request by tomas-stefano**
So I was trying some things to work the fin_cap app with the mas-cms-client gem and after 30 minutes I found that the spring was caching a lot of stuff, so I prefer to only add spring **if the app has a slow boot** (which is not the case atm).

### CODE REVIEW

**Comment by gotbadger** [comment]
IMO you should not remove spring as its part of the standard rails setup and deal with caching issues when they come up by restarting spring.

If you really want to clean the whole thing up you should also clean up the binstubs  see here: https://github.com/rails/spring#removal

**Comment by tomas-stefano** [comment]
@gotbadger yes I want to take rid of the whole thing. Thank you for the bin stubs tip and the link! I already removed the binstubs as the documentation suggests.

**Comment by Tr4pSt3R** [comment]
@tomas-stefano if you truly want to [disable Spring](https://github.com/rails/spring#environment-variables) this on a temporal basis you can set this environmental variable. It's sounds like a much easier deal for when we want to re-introduce this feature in the future. #futurefeature

```DISABLE_SPRING - If set, Spring will be bypassed and your application will boot in a foreground process```
https://github.com/rails/spring#temporarily-disabling-spring

**Comment by tomas-stefano** [comment]
I don't know, I still don't like the idea of things caching for myself without I asked them to do it for me. The other way around of disabling sounds wrong to me. I invested some precious time investigating something and when I see what was the problem, it was the spring caching things. Anyway we don't have the problem the spring wants to solve it and add it back it is straight forward so I don't see a problem disabling it. But I am happy if the team wants to continue to use then I am fine.

**Comment by Tr4pSt3R** [comment]
@tomas-stefano I'd only ask for _Spring_ to remain because it's become a fundamental part of how Rails works. If you were to disable it via the env var it will be more suited for those who have not stumbled into this issue yet/. Wdyt? Is it okay to disable it instead or should we still remove them gem for now and re-instate it in the future?

**Comment by tomas-stefano** [comment]
I still undecided the best way. I will see here the best way to disable for me, so I will close the PR.

**Pull request closed without merging**
