### PR TITLE
[DEV APPROVED] - 9425 Fix nested bullets indentation

### PR DESCRIPTION
**Pull request by your**
[TP 9425](https://moneyadviceservice.tpondemand.com/entity/9425-replicate-the-formatting-of-the-current)

This is the second part of the fix provided here: https://github.com/moneyadviceservice/cms/pull/476

Co-Authored-By: Tomas D'Stefano <tomas_stefano@successoft.com>

### CODE REVIEW

**Comment by masbuild** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There are code changes, but no corresponding tests. Please include tests if this PR introduces any modifications in behavior. If this is a refactor PR, please ignore the message.Refer to our mas standards guides about opening a PR<a href="link-to-the-mas-standards-about-opening-a-pr">here</a></td>
    </tr>
  </tbody>
</table>

At Money Advice Service, we use Danger gem, to ensure that our commits and pull requests follow [standards](https://github.com/moneyadviceservice/mas-standards/blob/master/Dangerfile). If you think one of the points here has been raised in error (or shouldn't be in our standards), open an issue or pull request on [our Danger config](https://github.com/moneyadviceservice/mas-standards).

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by tomas-stefano** [comment]
Can I have a second review, please? cc @davidtrussler @rhianwatkins1 @willhall88 
I fix the issue on q.a when the bullet's types does not appear on the homepage: https://fincap.qa.dev.mas.local/
I would like to put everything inside the .body-content but the #176 still is not merged so that's what I need to do it for now.

**Comment by rhianwatkins1** [comment]
I don't think it's a good idea putting in code as a quick fix because the actual solution to the problem hasn't been able to get time in the pipeline yet. 
Personally, I think you should either just put the body-content class on, or we need to work out getting 176 in there as well

**Comment by rhianwatkins1** [comment]
Yes, that sounds good to me!

**Comment by tomas-stefano** [comment]
@rhianwatkins1 ♻️

**Comment by rhianwatkins1** [comment]
I've just pulled your branch into my 176 and it works as intended, my only concern is that there is an awful lot of margin. I've had a chat with David about it and we think 
```margin-left: $baseline-unit * 3;```
is a good amount, it would put the nested bullet inline with the indent from it's parent.

Are you happy to decrease the margin?

If not (i.e. you've been told to make it that big or something) can we still then change it to be
```margin-left: $baseline-unit * 10;``` 
Either 10 or 11, just to match with how we normally do our spacing?

Other than that, it looks good to me

**Comment by tomas-stefano** [comment]
@rhianwatkins1 excellent suggestion. I used the same margin size from the actual fincap site, since there was nothing specified the ident size. I applied the `margin-left: $baseline-unit * 3;`. Thank you.

**Comment by rhianwatkins1** [comment]
Perfect!!

**Pull request merged**
